language: cpp

dist: trusty
sudo: required

notifications:
  email: false

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: COMPILER=g++-7
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env: COMPILER=g++-8

# Compilation on Clang 6.0 + libc++ fails because
# the <type_traits> template variables like std::is_same_v aren't defined

#   - compiler: clang
#     addons:
#       apt:
#         sources:
#           - ubuntu-toolchain-r-test
#           - llvm-toolchain-trusty-6.0
#         packages:
#           - clang-6.0
#           - libc++-dev
#           - libc++abi-dev
#     env:
#       - COMPILER=clang++-6.0
#       - CMAKE_FLAGS="-DCMAKE_CXX_FLAGS=-stdlib=libc++ -DCMAKE_EXE_LINKER_FLAGS=-lc++"

script:
  - uname -a
  - cmake --version
  - $COMPILER --version

  - mkdir bin
  - cd bin
  - cmake .. $CMAKE_FLAGS -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_CXX_COMPILER=$COMPILER
  - cmake --build .

  - ./Test
