version: '{build}'

shallow_clone: false

environment:
  MSBUILD_FLAGS: /verbosity:minimal /maxcpucount
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      COMPILER: Visual Studio 15 2017
      CMAKE_GEN: "Visual Studio 15 2017"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      COMPILER: Visual Studio 15 2017
      CMAKE_GEN: "Visual Studio 15 2017 Win64"

matrix:
  fast_finish: true

platform:
  - x86
  - x64
configuration: Debug

init:
  - uname -a
  - cmake --version
  - msbuild /version

install:
  - git submodule update --init --recursive

before_build:
  - mkdir bin
  - cd bin
  - cmake .. -G "%CMAKE_GEN%"

build_script:
  - echo foo
# - cmake --build . --config "%CONFIGURATION%" -- %MSBUILD_FLAGS%

test_script:
  - echo foo
# - "%CONFIGURATION%\\Test"
